# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "980f281051050817818f2c4d6b2aa2b7"
application_url = "https://storetranslatorapp-production.up.railway.app"
embedded = true
name = "storetranslatorapp"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_locales,write_locales,read_translations,write_translations,read_markets,write_markets"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  topics = [ "products/create", "products/update" ]
  uri = "/webhooks/products"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/compliance"

[auth]
redirect_urls = [
  "https://storetranslatorapp-production.up.railway.app/auth/callback",
  "https://storetranslatorapp-production.up.railway.app/auth/login",
  "https://storetranslatorapp-production.up.railway.app/auth/shopify/callback",
  "https://storetranslatorapp-production.up.railway.app/api/auth/callback"
]

[build]
automatically_update_urls_on_dev = false
include_config_on_deploy = true
